config/routes.rb
MyProject::Application.routes.draw do
  resources :circuits

  resources :body_parts

  resources :exercises

  resources :users

  resource :session

  root "exercises#index"

  

end

app/models/circuit.rb
class Circuit < ActiveRecord::Base
    has_many :circuit_exercises
    has_many :exercises, :through => :circuit_exercises

#this is to list all exercises which belong to a circuit
#e the grey part was my first version, the valid part is the much nicer improved code
def exercise_list
        #list=""
        #exercises.each do |e|
        #list += e.name
        #if e != exercises.last
        #    list += ", "
        #else
        #    list += "."
        #end
    #end
    #return list

    exercises.map {|e| e.name}.join(', ') + '.'
end

end

app/controllers/circuits_controller.rb
class CircuitsController < ApplicationController
  before_action :set_circuit, only: [:show, :edit, :update, :destroy]

  # GET /circuits
  # GET /circuits.json
  def index
    @circuits = Circuit.all
  end

  # GET /circuits/1
  # GET /circuits/1.json
  def show

  end

  # GET /circuits/new
  def new
    @body_parts = BodyPart.all
    @circuit = Circuit.new
  end

  # GET /circuits/1/edit
  def edit
     @body_parts = BodyPart.all
  end

  # POST /circuits
  # POST /circuits.json
  def create
    @circuit = Circuit.new(circuit_params)

    respond_to do |format|
      if @circuit.save
        format.html { redirect_to @circuit, notice: 'Circuit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @circuit }
      else
        format.html { render action: 'new' }
        format.json { render json: @circuit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /circuits/1
  # PATCH/PUT /circuits/1.json
  def update
    respond_to do |format|
      if @circuit.update(circuit_params)
        format.html { redirect_to @circuit, notice: 'Circuit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @circuit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /circuits/1
  # DELETE /circuits/1.json
  def destroy
    @circuit.destroy
    respond_to do |format|
      format.html { redirect_to circuits_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_circuit
      @circuit = Circuit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def circuit_params
      params.require(:circuit).permit(:name, :repetitions, :exercise_ids => [])
    end
end

app/helpers/circuits_helper.rb
module CircuitsHelper
end

app/views/circuits/_form.html.erb
<%= form_for(@circuit) do |f| %>
  <% if @circuit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@circuit.errors.count, "error") %> prohibited this circuit from being saved:</h2>

      <ul>
      <% @circuit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div>
  <table class="table table-striped">

    <thead>
    <tr><% @body_parts.each do |bp| %>
      <td> <%= bp.name  %></td>
      <% end %>
    </tr>
    </thead>

    <tbody>
      <tr>
        <% @body_parts.each do |bp| %>
      <td><%=   f.collection_check_boxes :exercise_ids, bp.exercises, :id, :name%>
                
       </td>
      <% end %>
    </tr>
    </tbody>

  </table>

</div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :autofocus => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<!--.collection_check_boxes, :exercise_ids, Exercise.all, :id, :name-->

app/views/circuits/edit.html.erb
<h1>Editing circuit</h1>

<%= render 'form' %>

<%= link_to 'Show', @circuit %> |
<%= link_to 'Back', circuits_path %>

app/views/circuits/index.html.erb
<h1>Listing circuits</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Exercises</th>
      <!--<th></th>-->
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @circuits.each do |circuit| %>
      <tr>
        <td><%= link_to circuit.name, circuit %></td>
        <td><%= circuit.exercise_list %></td>
       
        <!--<td><%= link_to 'Show', circuit %></td>-->
        <td><%= link_to 'Edit', edit_circuit_path(circuit) %></td>
        <td><%= link_to 'Delete', circuit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New Circuit', new_circuit_path, :class => "btn-success", :method => :get %>

app/views/circuits/new.html.erb
<h1>New circuit</h1>

<%= render 'form' %>

<%= link_to 'Back', circuits_path %>

app/views/circuits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @circuit.name %>
</p>

<p>
    <strong>Exercises:</strong>
    <%= @circuit.exercise_list%>
</p>

<%= link_to 'Edit', edit_circuit_path(@circuit) %> |
<%= link_to 'Back', circuits_path %>