config/routes.rb
MyProject::Application.routes.draw do
  resources :circuits

  resources :body_parts

  resources :exercises

  resources :users

  resource :session

  root "exercises#index"

  

end

app/models/body_part.rb
class BodyPart < ActiveRecord::Base
    has_many :exercises
    belongs_to :circuit

    def exercise_list
         exercises.map {|e| e.name}.join(', ')
    end

end

app/controllers/body_parts_controller.rb
class BodyPartsController < ApplicationController
  before_action :set_body_part, only: [:show, :edit, :update, :destroy]

  # GET /body_parts
  # GET /body_parts.json
  def index
    @body_parts = BodyPart.all
    case params[:sort]
    when "name"
       @body_parts = BodyPart.all.sort_by {|e| e.name }
    else
      @body_parts = BodyPart.all.sort_by {|e| e.name }
    end
  end

  # GET /body_parts/1
  # GET /body_parts/1.json
  def show
  end

  # GET /body_parts/new
  def new
    @body_part = BodyPart.new
  end

  # GET /body_parts/1/edit
  def edit
  end

  # POST /body_parts
  # POST /body_parts.json
  def create
    @body_part = BodyPart.new(body_part_params)

    respond_to do |format|
      if @body_part.save
        format.html { redirect_to @body_part, notice: 'Body part was successfully created.' }
        format.json { render action: 'show', status: :created, location: @body_part }
      else
        format.html { render action: 'new' }
        format.json { render json: @body_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /body_parts/1
  # PATCH/PUT /body_parts/1.json
  def update
    respond_to do |format|
      if @body_part.update(body_part_params)
        format.html { redirect_to @body_part, notice: 'Body part was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @body_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /body_parts/1
  # DELETE /body_parts/1.json
  def destroy
    @body_part.destroy
    respond_to do |format|
      format.html { redirect_to body_parts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_body_part
      @body_part = BodyPart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def body_part_params
      params.require(:body_part).permit(:name)
    end
end

app/helpers/body_parts_helper.rb
module BodyPartsHelper
end

app/views/Body_parts/_form.html.erb
<%= form_for(@body_part) do |f| %>
  <% if @body_part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@body_part.errors.count, "error") %> prohibited this body_part from being saved:</h2>

      <ul>
      <% @body_part.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :autofocus => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/Body_parts/edit.html.erb
<h1>Editing body_part</h1>

<%= render 'form' %>

<%= link_to 'Show', @body_part %> |
<%= link_to 'Back', body_parts_path %>

app/views/Body_parts/index.html.erb
<h1>These are the body parts for the exercises</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= "name"%></th>
      <!--<th></th>-->
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @body_parts.each do |body_part| %>
      <tr>
        <td><%= link_to body_part.name, body_part %></a></td>
        <!--<td><%= link_to 'Show', body_part %></td>-->
        <td><%= link_to 'Edit', edit_body_part_path(body_part) %></td>
        <td><%= link_to 'Delete', body_part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p> Add a new body part that you want to work out:</p>

<%= button_to 'New body part', new_body_part_path, :class => "btn-success", :method => :get %>

app/views/Body_parts/new.html.erb
<h1>Add a new part of your body to work out</h1>

<%= render 'form' %>

<%= link_to 'Back', body_parts_path %>

app/views/Body_parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @body_part.name %>
</p>

<%= link_to 'Edit', edit_body_part_path(@body_part) %> |
<%= link_to 'Back', body_parts_path %>